# Generated by Django 5.2 on 2025-05-10 12:55

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Avis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("utilisateur", models.CharField(max_length=100)),
                ("commentaire", models.TextField()),
                (
                    "note",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nom de la formation"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("professionnel", "Professionnel"),
                            ("langues", "Langues Vivantes"),
                        ],
                        max_length=20,
                        verbose_name="Type de formation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InfosPlateforme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MembreEquipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="equipe/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Partenaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="partenaires/"),
                ),
                ("site_web", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                ("avantages", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Inscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                ("date_of_birth", models.DateField(verbose_name="Date de naissance")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Adresse e-mail",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Pays"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Ville")),
                ("address", models.TextField(verbose_name="Adresse")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'inscription"
                    ),
                ),
                (
                    "formations",
                    models.ManyToManyField(
                        to="universe.formation", verbose_name="Formations choisies"
                    ),
                ),
            ],
        ),
    ]
